version: 2

jobs:
  build:
    macos:
      xcode: "9.0"

    environment:
    - ATOM_LINT_WITH_BUNDLED_NODE: "true"
    - APM_TEST_PACKAGES: ""
    - npm_config_clang: "1"
    - CC: clang
    - CXX: clang++
    - ATOM_GITHUB_FS_EVENT_LOG: "1"
    - MOCHA_TIMEOUT: "60000"
    - UNTIL_TIMEOUT: "30000"

    dependencies:
      override:
      - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
      - chmod u+x build-package.sh

    steps:
    - checkout
    - run:
        name: build-package.sh
        command:
        - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
        - chmod u+x build-package.sh
    - run:
        name: tests
        command: caffeinate -s ./build-package.sh
