language: objective-c
script: ./script/cibuild
env:
  global:
  - secure: "jKhyYrFgwLHApR4qYbsKBgRnLUq5INYGlwVwhHo4rLnhrfeIp3UPloshVe7tBBZjXAUwDn0h3VXPLY+l7wYFJZfmuruCDPxulpeimy3Grm4ac6ge/GsQPJT98e9SDpGJVbf6DE778a8A26k6bcc28Sr6ubjKGqEgiY5pIODzznk="
