language: objective-c
script: ./script/cibuild
env:
  global:
    - secure: "KH6AqQQYm0sDjIlawBVRfds7OWyZwpjlVLaequCth4h5mCC2SeVHwE+cU2GPBsKgtZHBFlNbYBlnqO3mtaUiS6qUqqSBm+gsJQJuLAW75NqGyylpjQs7n8bP9EErqslfN0TYqF+k3Crs8YN7PvH03MZx556WPNMBHgW8xFAorR8="
