parameters:
  atom_channel: dev
  atom_directory: Atom Dev

steps:
- powershell: |
    Set-StrictMode -Version Latest
    $script:ATOMROOT = "$env:AGENT_HOMEDIRECTORY/atom"

    Write-Host "Downloading latest Atom release"
    $source = "https://atom.io/download/windows_zip?channel=${{ parameters.atom_channel }}"
    $destination = "atom.zip"

    (New-Object System.Net.WebClient).DownloadFile($source, $destination)
    Expand-Archive -Path "atom.zip" -DestinationPath $script:ATOMROOT
  displayName: install Atom
- powershell: |
    Set-StrictMode -Version Latest
    $script:ATOMROOT = "$env:AGENT_HOMEDIRECTORY/atom"
    $script:APM_SCRIPT_PATH = "$script:ATOMROOT\${{ parameters.atom_directory }}\resources\app\apm\bin\apm.cmd"

    & "$script:APM_SCRIPT_PATH" ci
    if ($LASTEXITCODE -ne 0) {
      Write-Host "Dependency installation failed"
      $host.SetShouldExit($LASTEXITCODE)
      exit
    }
  displayName: install dependencies
