language: node_js
node_js: '8'
sudo: true
os: linux
dist: trusty

branches:
  only:
  - master
  - /^greenkeeper/.*$/

addons:
  apt:
    packages:
    - clang-3.3
    - build-essential
    - gnome-keyring
    - libsecret-1-dev
    - python-gnomekeyring

env:
  global:
  - npm_config_clang=1
  - CC=clang
  - CXX=clang++
  - ATOM_GITHUB_FS_EVENT_LOG=1
  - MOCHA_TIMEOUT=60000
  - UNTIL_TIMEOUT=30000
  - DISPLAY=":99"
  - ATOM_GITHUB_DISABLE_KEYTAR=1
  - ATOM_GITHUB_INLINE_GIT_EXEC=1
  - ATOM_CHANNEL=dev
  - ATOM=${HOME}/atom/usr/bin/atom-dev
  - APM=${HOME}/atom/usr/bin/apm-dev

notifications:
  email: false

install:
- npm install -g npm
- >
    curl -s -L "https://atom.io/download/deb?channel=$ATOM_CHANNEL"
    -H 'Accept: application/octet-stream'
    -o "atom.deb"
- >
    /sbin/start-stop-daemon --start --quiet
    --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
    --background --exec /usr/bin/Xvfb -- :99 -ac
    -screen 0 1280x1024x16
- dpkg-deb -x atom.deb "$HOME/atom"
- |
    echo "Atom version:"
    ${ATOM} --version
    echo "apm version:"
    ${APM} --version
- ${APM} ci || ${APM} install

before_script:
- eval $(echo -n "" | /usr/bin/gnome-keyring-daemon --login)
- eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start)
- dbus-launch /usr/bin/python -c "import gnomekeyring;gnomekeyring.create_sync('login', '');"

script:
- npm run test:coverage

after_script:
- npm run coveralls
