os: osx
language: node_js

node_js:
  - '4.4.7'

env:
  global:
    - secure: "O3FtYe/2JAVlm5+NSRFTe9hfzyUvMtzRkCzegZbh9DwAloB6OQKupdqnFbq6i8mSj6rmnlE84S/y729DYKnCZh/RU6bWKnlhoM5qW5pfHLvtgp1PhAKAPoo907wu+M7h9xQtSg33+DUvBfLxXMYGEtFMldDNQZezMYsdu6M+70iNvWKzhYG/H5opvt5cTqdJmCqwzm2iOWayAkyGkJlbwV5vjCs7NuMI2/sPzYRDGh1VVnnFOMT3idvrXv7EYYEDLGZ/Q92LmEcdOPqIqOTBdAjg5ungJoiMcZkR7PqD1fBWMat0G+d2jaGcHFCAkAZ6Bl7ADT2gG+gU43ANzN1UWfUqNRBZxPotfp0TAvhF0Ll6nxlNcjR3e4SfTe1GjFLNQSTkedad/378Z1sWeS1pl94Jdn6aZEcKpBqBfsz2e4vRdyzSG4NiLThDdM7k/cZAUx9kKy3zycD3+jgpnYygPv8xjD2ZmEyL0dzoCto+2oOQNvN8+UHmT0TQgsFTxXTFpni69nWuC/zr4O1TjwbOah2TsPe0eD//ntJaqAIxtUJ/toi/OcdEODY6gbw0vNuBl0KhyYGPac/cTMALsCMV5BG5q72X5rhKlFrjQ8nfXJOV6HXMGJMRtKJTW4MEzokf3yaEdL6ATaV3Y+F95hulh+F0STCa8I8wSdlK3Fvo9+w="
  matrix:
    - TRAVIS_BUILD_JOB=schemacheck
    - TRAVIS_BUILD_JOB=runtests ATOM_CHANNEL=stable ATOM_GITHUB_FS_EVENT_LOG=1
    - TRAVIS_BUILD_JOB=runtests ATOM_CHANNEL=beta ATOM_GITHUB_FS_EVENT_LOG=1

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: "cm17gjkIkp4cGPy5PTolNJlCGecqU0VptbEvv1HjqkrOnwPJibK9H8DVjmN4Xx3HTRPjlRIEOE/CmadFcJ0+jIsvId47AnrEOOWVQwAEWNpxDWd0zvVr0/TdKOm+9pPFo16I/1OtLT8keCs0WyoVfzC+p56dhSw+KR8I+0Zbwv/BVH/BYn3LsiCzNS/vp4bajcqLmq+23hderskpEHaX9HpbhYNy6nm3haZBYimvdSKkQdW7eSmwU5JZ6hdhUH5sqmIq5mRV1jppREQ86UF0CupSmZGPtvRK/EGEiCETB5vD7aSx9kPaxQ5P5YNG+Kq5mHNzj/k0ZrhMjdH6xoeSMjdW3Hn0gqc/zhy0qY/LeBSwVJFFq8Xy2K1SIDKYX/X5Jmo/ZIrJmN+p45+JHY5gxmtu1ckteeFtKpJye4WPmeYAGpmJDTgtLdGV6XWZGWXdMTBbOGcLsNtZrx5aCueuhiiOb6zFgydhMR63WBharkz39ABQIA3RVHwPmpe+HhJbM4+eijA2WPbTJxFxjBw+mwlakag0RfuERutRjmUI++JBdbB7xzEet1Cfyk1p833xYG3YlXZV+BHUzt6/0OFaIQYcqpryjtFS10GVQbeFdNbxhNig6MKQ8cirpra6JQafRUuTmBAxIP/ZmglF8h0ZwT8lMnNgTHa/QhdALmVNYBk="

install:
  - npm install -g npm

script:
  - ./script/cibuild
