language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - ATOM_CHANNEL=beta

script:
  - ./script/cibuild
  - npm run check

branches:
  only:
    - master
