jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  variables:
    display: ":99"
  steps:
  - bash: |
      set -x
      curl -s -L "https://atom.io/download/deb?channel=dev" \
        -H 'Accept: application/octet-stream' \
        -o 'atom-amd64.deb'
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
      dpkg-deb -x atom-amd64.deb /tmp/atom
      find /tmp/atom/usr/bin -type f
    displayName: install Atom
  - bash: /tmp/atom/usr/bin/apm ci
    displayName: install dependencies
  - bash: /tmp/atom/usr/bin/atom --test test/
    displayName: run tests
