version: "{build}"

platform: x64

branches:
    only:
      - master

clone_depth: 10

skip_tags: true

environment:
  APM_TEST_PACKAGES:
  ATOM_GITHUB_FS_EVENT_LOG: '1'

  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

install:
  - ps: Install-Product node 4
  - ps: choco install windbg
  - ps: Get-ChildItem -Recurse -Path 'C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\'

build_script:
  - ps: |-
      New-Item -Path "HKLM:\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps" -Force
      New-ItemProperty `
        -Path 'HKLM:\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps' `
        -Name DumpType -Value 2 -PropertyType DWORD -Force
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

artifacts:
  - path: "$(TEMP)\Atom Crashes\"
    name: minidumps

on_failure:
  - ps: |-
      $symPath = "SRV*c:\symbols\*http://msdl.microsoft.com/download/symbols;SRV*c:\symbols\*https://electron-symbols.githubapp.com;c:\Users\smash\src\crashy\build\Release"
      $files = Get-ChildItem -Path "$($env:TEMP)\Atom Crashes\*.dmp"
      ForEach ($file in $files) {
        Write-Output "Analyzing crash dump: $file"
        'C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe' `
          -y $symPath -z $file -c '!analyze -v; q'
      }

test: off
deploy: off
