version: "{build}"

platform: x64

branches:
    only:
      - master

clone_depth: 10

skip_tags: true

environment:
  APM_TEST_PACKAGES:
  ATOM_GITHUB_FS_EVENT_LOG: '1'

  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

install:
  - ps: Install-Product node 4

build_script:
  - ps: |-
      New-Item -Path "HKLM:\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps" -Force
      New-ItemProperty `
        -Path 'HKLM:\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps' `
        -Name DumpType -Value 2 -PropertyType DWORD -Force
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

on_failure:
  - ps: |-
      $files = Get-ChildItem "$($env:LOCALAPPDATA)\CrashDumps"
      Write-Output $files

test: off
deploy: off
